name: mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # L10n
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  easy_localization: ^3.0.1

  # Architecture, DI
  flutter_riverpod: ^2.2.0
  riverpod_annotation: ^1.2.1

  # Networking
  dio: ^4.0.6

  # UI
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_markdown: ^0.6.14
  flutter_portal: ^1.1.3
  flutter_svg: ^2.0.2
  image_picker: ^0.8.6+2
  infinite_scroll_pagination: ^3.2.0
  flutter_form_builder: ^7.8.0
  form_builder_validators: ^8.5.0

  # Routing
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.5

  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Local storage
  shared_preferences: ^2.0.18

  # Sentry
  sentry_dio: ^6.20.1
  sentry_flutter: ^6.20.1
  sentry_logging: ^6.20.1

  # Utils
  collection: ^1.16.0
  flutter_launcher_icons: ^0.11.0
  pretty_dio_logger: ^1.2.0-beta-1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_gen_runner: ^5.2.0
  riverpod_generator: ^1.2.0
  very_good_analysis: ^4.0.0+1

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
